# Generated by Django 4.0.3 on 2024-01-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(default=2, upload_to='img'),
            preserve_default=False,
        ),
    ]
